### ISSUE TITLE
Variable als Auslöser: Aktualisierung / Änderung

### ISSUE THREAD

**Issue by papaschlumpf2000** [symcon/Benachrichtigung#6]
Hallo zusammen,
ist es möglich eine Unterscheidung nach Änderung oder Aktualisierung der gewählten Auslöser-Variable einzuführen, dass das Benachrichtigungsmodul auslöst? (Also wie man es bei Ereignissen in IPS auch kann.)
Ich habe gerade das Problem, dass meine Variable immer wieder vom Hardwaretrigger auf True gesetzt wird und ich trotz Quittierung immer wieder in die Benachrichtigungsstufen springe. Einmal quittieren sollte reichen bis der Auslöser einmal false war.
Danke!

**Comment by paresy** [comment]
Wir schauen uns das an und melden uns im Beitrag im Forum.
